joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125

# My PD Controller
cartesian_pd_controller:
  type: effort_controllers/CartesianPDController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint    


cartesian_impedance_controller:
  type: effort_controllers/CartesianImpedanceController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  print_data: true
  home_configuration:
    pose:
      x: 0.5
      y: 0.0
      z: 0.0
      roll: 0.0
      pitch: 1.57
      yaw: 0.0
    joints:
      shoulder_pan_joint: -0.187932
      shoulder_lift_joint: -0.922357
      elbow_joint: 1.99554
      wrist_1_joint: -2.62668
      wrist_2_joint: -1.57547
      wrist_3_joint: -0.186816

cartesian_adaptive_controller:
  type: effort_controllers/CartesianAdaptiveController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint  
  print_data: true
  home_configuration:
    pose:
      x: 0.5
      y: 0.0
      z: 0.0
      roll: 0.0
      pitch: 1.57
      yaw: 0.0
    joints:
      shoulder_pan_joint: -0.187932
      shoulder_lift_joint: -0.922357
      elbow_joint: 1.99554
      wrist_1_joint: -2.62668
      wrist_2_joint: -1.57547
      wrist_3_joint: -0.186816