joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125

# My PD Controller
cartesian_pd_controller:
  type: effort_controllers/CartesianPDController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint    


cartesian_impedance_controller:
  type: effort_controllers/CartesianImpedanceController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  print_data: false


cartesian_adaptive_controller:
  type: effort_controllers/CartesianAdaptiveController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint  
  print_data: false  